### ISSUE TITLE
能否编译带一下kmod-usb-printer打印机内核包

### ISSUE THREAD

**Issue by romeo1978** [xiaomeng9597/Actions-iStoreOS-For-RK35XX#3]
感谢发布这个istoreos编译包，我是panther x2，下载了06.07日编译的镜像包iStoreOS 22.03.6 2024060700 by xiaomeng9597

准备安装HP 1020plus打印机，是USB打印机，按网上教程安装好p910nd打印服务和sihp1020.dl驱动程序，但往打印机发送打印没任何反应。
下载驱动是执行命令cat /etc/sihp1020.dl >/dev/usb/lp0 ， 执行发现打印机也没有反应
执行iStoreOS:~# lsusb -D /dev/usb/lp0 报错：
Cannot open /dev/usb/lp0

看来内核没安装好usb打印机，用opkg安装kmod-usb-printer报错：
iStoreOS:~# opkg install kmod-usb-printer
Unknown package 'kmod-usb-printer'.
Collected errors:
 * opkg_install_cmd: Cannot install package kmod-usb-printer.
仓库中没有kmod-usb-printer包；
查看lib目录下没有kmod-usb-printer库：
iStoreOS:/lib# find . |grep usb
./modules/5.10.201/ath6kl_usb.ko
./modules/5.10.201/dmx_usb.ko
./modules/5.10.201/ezusb.ko
./modules/5.10.201/ledtrig-usbport.ko
./modules/5.10.201/mt76-usb.ko
./modules/5.10.201/mt7663-usb-sdio-common.ko
./modules/5.10.201/mt76x02-usb.ko
./modules/5.10.201/plusb.ko
./modules/5.10.201/rsi_usb.ko
./modules/5.10.201/rtl_usb.ko
./modules/5.10.201/rtw_usb.ko
./modules/5.10.201/snd-usb-audio.ko
./modules/5.10.201/snd-usbmidi-lib.ko
./modules/5.10.201/ti_usb_3410_5052.ko
./modules/5.10.201/ums-usbat.ko
./modules/5.10.201/usb-serial-simple.ko
./modules/5.10.201/usb_f_uvc.ko
./modules/5.10.201/usb_wwan.ko
./modules/5.10.201/usbatm.ko
./modules/5.10.201/usbhid.ko
./modules/5.10.201/usbnet.ko
./modules/5.10.201/xr_usb_serial_common.ko
./upgrade/keep.d/usbmuxd

继续百度说kmod包必须要编译到内核中，用opkg没法安装，看来是镜像里没有编译这个包，能否在后续版本中编译带入一下（kmod-usb-printer还有依赖的kmod-usb-core），多谢！

**Comment by xiaomeng9597** [comment]
> 感谢发布这个istoreos编译包，我是panther x2，下载了06.07日编译的镜像包iStoreOS 22.03.6 2024060700 by xiaomeng9597
> 
> 准备安装HP 1020plus打印机，是USB打印机，按网上教程安装好p910nd打印服务和sihp1020.dl驱动程序，但往打印机发送打印没任何反应。 下载驱动是执行命令cat /etc/sihp1020.dl >/dev/usb/lp0 ， 执行发现打印机也没有反应 执行iStoreOS:~# lsusb -D /dev/usb/lp0 报错： Cannot open /dev/usb/lp0
> 
> 看来内核没安装好usb打印机，用opkg安装kmod-usb-printer报错： iStoreOS:~# opkg install kmod-usb-printer Unknown package 'kmod-usb-printer'. Collected errors:
> 
> * opkg_install_cmd: Cannot install package kmod-usb-printer.
>   仓库中没有kmod-usb-printer包，
>   继续百度说kmod包必须要编译到内核中，用opkg没法安装，看来是镜像里没有编译这个包，能否在后续版本中编译带入一下（kmod-usb-printer还有依赖的kmod-usb-core），多谢！
请提供具体报错日志，另外kmod-usb-printer，kmod-usb-core有预装到系统里面的

**Comment by xiaomeng9597** [comment]
请提供具体报错日志，另外kmod-usb-printer，kmod-usb-core有预装到系统里面的

**Comment by xiaomeng9597** [comment]
留下联系方式

**Comment by xiaomeng9597** [comment]
留下联系方式
![Screenshot_2024-06-10-20-28-49-802_mark via](https://github.com/xiaomeng9597/Actions-iStoreOS-For-RK35XX/assets/49544781/cd5e68b1-55ec-47c4-9b91-f19ee1a3da5c)

**Comment by romeo1978** [comment]
> 留下联系方式

多谢大佬，联系493144090@qq.com，晚上我截图错误信息你帮忙看下，多谢！

**Comment by xiaomeng9597** [comment]
能用了吗？我没打印机测不了，已经添加USB打印机那个插件了，在网络储存里面
