### ISSUE TITLE
安装luci-i18n-v2raya-zh-cn报了一个下面找不到kmod-nft-tproxy依赖的错误

### ISSUE THREAD

**Issue by romeo1978** [xiaomeng9597/Actions-iStoreOS-For-RK35XX#4]
大佬帮忙看下，安装不了v2raya：

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-tproxy for v2raya
 * pkg_hash_fetch_best_installation_candidate: Packages for v2raya found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-v2raya-zh-cn:
 * 	kmod-nft-tproxy
 * opkg_install_cmd: Cannot install package luci-i18n-v2raya-zh-cn.

**Comment by xiaomeng9597** [comment]
istoreos软件源仓库里面缺少kmod-nft-tproxy，你得自己找一下其他软件源仓库里面有没有这个，补上后才行

**Comment by xiaomeng9597** [comment]
你是不是要安装OpenClash，进入这两个仓库里面下载对应的脚本并且下载然后在系统商店里面离线安装

https://github.com/AUK9527/Are-u-ok/tree/main/apps

https://github.com/bcseputetto/Are-u-ok/releases/tag/iStoreOS

**Comment by romeo1978** [comment]
> 你是不是要安装OpenClash，进入这两个仓库里面下载对应的脚本并且下载然后在系统商店里面离线安装
> 
> https://github.com/AUK9527/Are-u-ok/tree/main/apps
> 
> https://github.com/bcseputetto/Are-u-ok/releases/tag/iStoreOS

好的，我试下openclash看
